### ISSUE TITLE
I got an error 

### ISSUE THREAD

**Issue by Ango87** [mingfunwong/all-bitcoin-private-key#21]
@mingfunwong 
yarn start
yarn run v1.22.17
$ ng serve
Compiling @angular/animations : es2015 as esm2015 Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/cdk/table : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/tooltip : es2015 as esm2015
Compiling @angular/material/sort : es2015 as esm2015
Compiling @angular/material/toolbar : es2015 as esm2015
Compiling @angular/material/progress-spinner : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @angular/material/paginator : es2015 as esm2015
Compiling @angular/material/table : es2015 as esm2015
⠦ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/blink/all-bitcoin-private-key/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/blink/all-bitcoin-private-key/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/blink/all-bitcoin-private-key/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/blink/all-bitcoin-private-key/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/blink/all-bitcoin-private-key/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/blink/all-bitcoin-private-key/node_modules/loader-runner/lib/LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (/home/blink/all-bitcoin-private-key/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:48:13)
    at processResource (/home/blink/all-bitcoin-private-key/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/home/blink/all-bitcoin-private-key/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/home/blink/all-bitcoin-private-key/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/blink/all-bitcoin-private-key/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/blink/all-bitcoin-private-key/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/blink/all-bitcoin-private-key/node_modules/webpack/lib/Compilation.js:739:10)
    at /home/blink/all-bitcoin-private-key/node_modules/webpack/lib/Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by LetsMelon** [comment]
Run `export NODE_OPTIONS=--openssl-legacy-provider` before `ng serve`
